name: Go
on:
  release:
    types:
      - created

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v5
      with:
        go-version: '1.22'
    - run: mkdir dist
    - run: go get
    - run: GOARCH=windows GOARCH=amd64 go build -o dist/dummy_ssh_server_win.exe
    - run: GOARCH=linux GOARCH=amd64 go build -o dist/dummy_ssh_server_linux
    - name: Upload build-artifacts
      uses: skx/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: "./dist/dummy_ssh_server_*"
